function model = setProtPoolSize(model,poolSize,modelAdapter)
% setProtPoolSize
%   Sets the limit of the total protein usage in the model.
%
% Input:
%   model           ec-model that was generated by makeEcModel, or loaded from
%                   an earlier run. Not compatible with ec-models generated by
%                   earlier GECKO versions (pre 3.0).
%   poolSize        The upper bound of the prot_pool_exchange rxn. If omitted ([])
%                   the value will be read from the model adapter.
%   modelAdapter    a loaded model adapter (Optional, will otherwise use the
%                   default model adapter).
%
% Output:
%   model           ec-model with protein pool constraint set
%
% Usage: model = setProtPoolSize(model,poolSize,modelAdapter);

if nargin < 3 || isempty(modelAdapter)
    modelAdapter = ModelAdapterManager.getDefaultAdapter();
    if isempty(modelAdapter) && (nargin<2 || isempty(poolSize))
        error('Either send in a modelAdapter or set the default model adapter in the ModelAdapterManager.')
    end
end

if nargin<2 || isempty(poolSize)
    poolSize = modelAdapter.getParameters().standardProtPoolSize;
end

model.ub(strcmp(model.rxns, 'prot_pool_exchange')) = poolSize;

end

