Description of ModelAdapter
Home > src > geckomat > model_adapter > ModelAdapter.m
ModelAdapter
PURPOSE
Abstract Base class for adapters for different species
SYNOPSIS
This is a script file.
DESCRIPTION
Abstract Base class for adapters for different species
CROSS-REFERENCE INFORMATION
This function calls:
ModelAdapter Abstract Base class for adapters for different species
This function is called by:
ModelAdapter Abstract Base class for adapters for different species
adapterTemplate
SUBFUNCTIONS
function parameters = getParameters(obj)
function model = manualModifications(obj,model)
function genes = getUniprotCompatibleGenes(obj,inGenes)
function uniprotIDs = getUniprotIDsFromTable(obj,modelGenes)
function folder = getBrendaDBFolder(obj)
function x = getPhylDistStructPath(obj)
SOURCE CODE
%Abstract Base class for adapters for different species
classdef (Abstract) ModelAdapter
    methods (Abstract)
        [spont,spontRxnNames] = getSpontaneousReactions(obj,model);
    end
    methods
        %not really needed, we could access it directly. Not very nice, but practical
        function parameters = getParameters(obj)
            parameters = obj.params;
        end
        %This allows for changing parameters in an adapter without
        %creating a new class. May be convenient, although less clean
        %function obj = setParameters(obj, parameters)
        %    obj.mParams = parameters;
        %end
        function model = manualModifications(obj,model) %default is to do nothing
        end
        %The genes returned here should match the gene id set in the parameter params.uniprotGeneIdField
        function genes = getUniprotCompatibleGenes(obj,inGenes)
            genes = inGenes;
        end
        function uniprotIDs = getUniprotIDsFromTable(obj,modelGenes)
            conversionTable = fullfile(obj.params.path,'data','uniprotConversion.tsv');
            if exist(conversionTable,'file')
                fID=fopen(conversionTable,'r');
                conversionTable = textscan(fID,'%q %q','Delimiter','\t','HeaderLines',1);
                fclose(fID);
                modelIDs    = conversionTable{1,1};
                uniprots    = conversionTable{1,2};
                [a,b] = ismember(modelGenes,modelIDs);
                uniprotIDs  = strings(numel(modelGenes),1);
                uniprotIDs(a)  = uniprots(b(a));
                disp('The model genes are matched to Uniprot via the table at data/uniprotConversion.tsv')
            else
                uniprotIDs = modelGenes;
            end
        end
        function folder = getBrendaDBFolder(obj)
            folder = fullfile(findGECKOroot(),'databases');
        end
        function x = getPhylDistStructPath(obj)
            x =  fullfile(findGECKOroot(),'databases','PhylDist.mat');
        end
    end
    %To have the params public is a bit "ugly", but very practical
    %if we want to change a parameter
    properties (Access = public)
        params;
    end
end