blank_issues_enabled: true
contact_links:
  - name: Gitter Channel
    url: https://gitter.im/SysBioChalmers/GECKO
    about: You may also ask questions (or contribute with answers) at the GECKO Gitter channel.
