function [rmse_samples, exp, simulated] = rmsecal_samples(ecModel, samples, data, objective, biomassRxns, highObjW)
% rmsecal
%    Calculate RMSE between experimental data and simulations for a set of
%    samples
%
% Input:
%   ecModel         ecModel that was generated by makeEcModel, or loaded from
%                   an earlier run. Not compatible with ecModels generated by
%                   earlier GECKO versions (pre 3.0)
%   samples         samples to use to calculate error
%   data            experimental data to be used to calculate RMSE: rxns in rxns
%                   field and experimental data in exp field
%   objective       objective reaction
%   biomassRxns     biomass reaction(s) to calculate number of carbons for
%                   normalization (optional, default [])
%   highObjW        multiply the value of the objective function to weigh
%                   it more in the rmse calculation (optional, default =
%                   10)
%
% Output:
%   rmse_samples    RMSE calculated for every sample
%   exp             flux values from input data (only for one sample)
%   simulated       values from simulations (only for one sample)


if nargin < 6 
    highObjW = 10;
end

if nargin < 5 
    biomassRxns = [];
end

% Number of steps equal to sample size
nstep = width(samples);
% Variable to save RMSE results
rmse_samples = zeros(1,nstep);
% Create progress bar
h = waitbar(0, 'Processing...');
for k=1:nstep
    value = samples(:,k);
    ecModel.ec.concs = value;
    ecModel = constrainEnzConcs(ecModel);
    % Run function rmsecal if data is provide in data.exp 
    if ~isempty(data.exp)
        [rmse, exp, simulated] = rmsecal(ecModel, data, objective, biomassRxns, highObjW);
    else
        rmse = [];
        exp = [];
        simulated = [];
    end
    % Save RMSE 
    rmse_samples(1,k) = rmse;
    % Only output simulated result for one generation
    if nstep ~= 1
        simulated = [];
        exp = [];
    end
    waitbar(k/nstep, h, sprintf('Sample %d/%d', k, nstep));
end
close(h);
end