function rmse = abc_max(ecModel,fluxData,maxGrowth,rxn2block)
% abc_max
%   Internal function in BayesianSensitivityTuning. Gets the average RMSE for
%   a certain set of growth data and kcats.
%
% Input:
%   ecModel       ecModel that was generated by makeEcModel, or loaded from
%                 an earlier run. Not compatible with ecModels generated by
%                 earlier GECKO versions (pre 3.0).
%   fluxData      Growth data loaded from file.
%   maxGrowth     Max growth data loaded from file.
%   rxn2block     List of reactions to block, could be read from file.
%
% Output:
%   rmse          The average RMSE


%% First test with flux data
if ~isempty(fluxData)
    rmse_1 = rmsecal(ecModel,fluxData,true,rxn2block);
else
    rmse_1 = [];
end
%% Second test with maximum growth on various carbon sources
if ~isempty(maxGrowth)  % simulate the maximal growth rate
    rmse_2 = rmsecal(ecModel,maxGrowth,false,rxn2block);
else
    rmse_2 = [];
end
    
%% Combine results
rmse        = mean([rmse_1,rmse_2],'omitnan');
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function rmse = rmsecal(ecModel,data,constrain,rxn2block)

rmseList = zeros(length(data.conds),1);
for i = 1:length(data.conds)

    % Set carbon source
    [~,exchIdx] = ismember(data.conds,data.exchMets);
    % Set all other carbon sources to zero
    model_tmp = setParam(ecModel,'lb',data.exchRxnIDs(unique(exchIdx)),0);
    % Only allow condition-specific carbon source
    if constrain % If RMSE is calculated from flux data, then constrain carbon uptake
        model_tmp = setParam(model_tmp,'lb',data.exchRxnIDs(exchIdx(i)),data.exchFluxes(i));
    else % If RMSE is calculated from max growth, then do not constrain carbon uptake
        model_tmp = setParam(model_tmp,'lb',data.exchRxnIDs(exchIdx(i)),-1000);
    end
    
    % Remove carbon source exchange from rxn2block
    rxn2blockIter = rxn2block;
    rxn2blockIter(strcmp(rxn2blockIter,data.exchRxnIDs(exchIdx(i)))) = [];

    % Make anaerobic if relevant
    o2Flux = data.exchFluxes(i,strcmp('oxygen',data.exchMets));
    if o2Flux == 0
        model_tmp = anaerobicModel_GECKO(model_tmp);
    end
    
    sol = solveLP(model_tmp);
    if checkSolution(sol)
        bioRxn          = getIndexes(model_tmp,data.biomass,'rxns');
        % Assume that biomass contains 41 Cmmol/gDCW
        bioMeas         = data.grRate(i) * 41;
        bioSim          = sol.x(bioRxn) * 41;

        if constrain
            fluxToCheck     = ~isnan(data.exchFluxes(i,:));
            fluxRxnIdx      = getIndexes(model_tmp,data.exchRxnIDs(fluxToCheck),'rxns');
            cNormMeasFlux   = model_tmp.excarbon(fluxRxnIdx) .* transpose(data.exchFluxes(i,fluxToCheck));
            cNormSimFlux    = model_tmp.excarbon(fluxRxnIdx) .* sol.x(fluxRxnIdx);

            % Make sure that selected exchange reactions have zero flux
            blockRxnIdx     = getIndexes(model_tmp,rxn2blockIter,'rxns');
            blockSim        = sol.x(blockRxnIdx) .* model_tmp.excarbon(blockRxnIdx);
            blockMeas       = zeros(numel(blockSim),1);

            measured    = [cNormMeasFlux; bioMeas; blockMeas];
            simulated   = [cNormSimFlux; bioSim; blockSim];
        else
            measured    = bioMeas;
            simulated   = bioSim;
        end
        rmseList(i) = sqrt(mse(measured,simulated));
    else
        rmseList(i) = NaN;
    end
end
rmseList(isnan(rmseList)) = 99; % High penalty for models that failed
rmse = mean(rmseList);
end
