function rmse = abc_max(ecModel,fluxData,maxGrowth,rxn2block)
% abc_max
%   Internal function in BayesianSensitivityTuning. Gets the average RMSE for
%   a certain set of growth data and kcats.
%
% Input:
%   ecModel       ecModel that was generated by makeEcModel, or loaded from
%                 an earlier run. Not compatible with ecModels generated by
%                 earlier GECKO versions (pre 3.0).
%   fluxData      Growth data loaded from file.
%   maxGrowth     Max growth data loaded from file.
%   rxn2block     List of reactions to block, could be read from file.
%
% Output:
%   rmse          The average RMSE


%% First test with flux data
if ~isempty(fluxData)
    rmse_1 = rmsecal(ecModel,fluxData,true,rxn2block);
else
    rmse_1 = [];
end
%% Second test with maximum growth on various carbon sources
if ~isempty(maxGrowth)  % simulate the maximal growth rate
    rmse_2 = rmsecal(ecModel,maxGrowth,false,rxn2block);
else
    rmse_2 = [];
end
    
%% Combine results
rmse        = mean([rmse_1,rmse_2],'omitnan');
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function rmse = rmsecal(ecModel,data,constrain,rxn2block)

for i = 1:length(data(:,1))

    exp = cell2mat(data(i,3:11)); % u sub ace eth gly pyr ethyl_acetate co2 o2
    exp = (exp.*[1,-1,1,1,1,1,1,1,-1])';
    ex_mets = {'growth',[data{i,2},' exchange'],'acetate exchange','ethanol exchange','glycerol exchange','pyruvate exchange','ethyl acetate exchange','carbon dioxide exchange','oxygen exchange'};
    [~,idx] = ismember(ex_mets,ecModel.rxnNames);
    model_tmp = ecModel;

    model_tmp = changeMedia(model_tmp,'D-glucose',data{i,16});%TODO: These are currently hard-coded for yeast-GEM, add to adapter
    %Stop import/export of acetate and acetaldehyde
    model_tmp = setParam(model_tmp,'eq','r_1634',0); %TODO: These are currently hard-coded for yeast-GEM, add to adapter
    model_tmp = setParam(model_tmp,'eq','r_1631',0); %TODO: These are currently hard-coded for yeast-GEM, add to adapter

    if strcmp(data(i,14),'anaerobic') ||strcmp(data(i,14),'limited')
        model_tmp = anaerobicModel_GECKO(model_tmp);
    end
    if strcmp(data(i,14),'limited')
        model_tmp.lb(strcmp(model_tmp.rxnNames,'oxygen exchange')) = -5;%TODO: Currently hard-coded for yeast
    end
    if ~constrain
        %No export of glucose
        model_tmp.lb(strcmp(model_tmp.rxns,'r_1714')) = 0; %TODO: Currently hard-coded for yeast
        model_tmp.lb(strcmp(model_tmp.rxns,ecModel.rxns(idx(2)))) = -1000; % not constrain the substrate usage
    else
        %No export of glucose
        model_tmp.lb(strcmp(model_tmp.rxns,'r_1714')) = 0;%TODO: Currently hard-coded for yeast
        if isnan(exp(2))
            model_tmp.lb(idx(2)) = -1000;
        else
            model_tmp.lb(idx(2)) = exp(2);
        end
    end

     sol_tmp = solveLP(model_tmp);
    if checkSolution(sol_tmp)
        sol(:,i) = sol_tmp.x;

        tmp = ~isnan(exp);
        excarbon = ecModel.excarbon(idx);
        excarbon(excarbon == 0) = 1;
        exp_tmp = exp(tmp).*excarbon(tmp);
        simulated_tmp = sol(idx(tmp),i).*excarbon(tmp); % normalize the growth rate issue by factor 10

        % all zeros for blocked exchange mets exchange
        rxnblockidx = ismember(model_tmp.rxns,setdiff(rxn2block,model_tmp.rxns(idx(2))));
        simulated_block = sol(rxnblockidx,i).* ecModel.excarbon(rxnblockidx); %
        simulated_block = simulated_block(simulated_block~=0);
        exp_block = zeros(numel(simulated_block),1);
        if constrain
            rmse_tmp(i) = sqrt(mse([exp_tmp;exp_block], [simulated_tmp;simulated_block]));
        else
            if length(exp_tmp) >= 2
                rmse_tmp(i) = sqrt(mse(exp_tmp(1:2), simulated_tmp(1:2)));
            else
                rmse_tmp(i) = sqrt(mse(exp_tmp(1), simulated_tmp(1)));
            end

        end
    else
        rmse_tmp(i) = NaN;
    end
end
rmse_tmp(isnan(rmse_tmp)) = []; %we just skip any case without solution, they are pretty rare, but exist
rmse = sum(rmse_tmp)/length(data(:,1));

    function err = mse(y,x)
        err = (norm(x(:)-y(:),2).^2)/numel(x);
    end
end
