function model = addCarbonNum(model)
% addCarbonNum
%   Adds a carbon number field to the model.
%
% Input:
%   model           ecModel that was generated by makeEcModel, or loaded from
%                   an earlier run. Not compatible with ecModels generated by
%                   earlier GECKO versions (pre 3.0).
% Output:
%   model           ecModel
%

% get carbonnum for each exchange rxn to further calculation of error
model.excarbon = zeros(1,length(model.rxns));
[EXrxn, EXrxnIdx] = getExchangeRxns(model);
[CarbonNum,EXfors] = getcarbonnum(model,EXrxn);
model.excarbon(EXrxnIdx) = CarbonNum;
model.excarbon(strcmp(model.rxnNames,'growth')) = 41;

end
