function [ecModel, rmseTrace, kcatTrace, stdTrace] = bayesianSensitivityTuning(ecModel,kcatStd,modelAdapter)
% bayesianSensitivityTuning
%   Modifies kcats to better fit experimental data. Currently only works with
%   light models.
%
% Input:
%   ecModel         ecModel that was generated by makeEcModel, or loaded from
%                   an earlier run. Not compatible with ecModels generated by
%                   earlier GECKO versions (pre 3.0).
%   kcatStd         vector of same length as ecModel.ec.kcat, with the
%                   initial standard deviations (SD) for the kcat values.
%                   By default, kcatStd is set by multiplying kcat values
%                   with params.bayesian.initSDmultiplDef, or by source-
%                   specific multipliers specified in params.bayesian.
%                   kcatSources and params.bayesian.initSDmultipl. Instead,
%                   it is also possible to provide a custom kcatStd vector.
%   modelAdapter    a loaded model adapter (Optional, will otherwise use the
%                   default model adapter).
%
% Output:
%   model           ecModel with new kcats, not applied.
%
if nargin < 3 || isempty(modelAdapter)
    modelAdapter = ModelAdapterManager.getDefault();
    if isempty(modelAdapter)
        error('Either send in a modelAdapter or set the default ecModel adapter in the ModelAdapterManager.')
    end
end

%% Load hyperparameters
params = modelAdapter.params;
initSDmultiplDef    = params.bayesian.initSDmultiplDef;
kcatSources         = params.bayesian.kcatSources;
initSDmultipl       = params.bayesian.initSDmultipl;
samples1            = params.bayesian.samples1;
samples2_5          = params.bayesian.samples2_5;
samples6_end        = params.bayesian.samples6_end;
targetAccept1       = params.bayesian.targetAccept1;
targetAccept2_5     = params.bayesian.targetAccept2_5;
targetAccept6_end   = params.bayesian.targetAccept6_end;
minKeep             = params.bayesian.minKeep;
maxKeep             = params.bayesian.maxKeep;
rMax                = params.bayesian.rMax;
cExpl               = params.bayesian.cExpl;
tauResidual         = params.bayesian.tauResidual;
rmseThreshold       = params.bayesian.rmseThreshold;
maxGenerations      = params.bayesian.maxGenerations;
basePath            = params.path;

%% Define initial kcat distributions
if nargin < 2 || isempty(kcatStd)
    kcatStd     = ecModel.ec.kcat .* initSDmultiplDef;
    for i = 1:numel(kcatSources)
        selKcats            = strcmpi(ecModel.ec.source,kcatSources{i});
        kcatStd(selKcats)   = ecModel.ec.kcat(selKcats) .* initSDmultipl(i);
    end
end

%% Load data
% fluxData = data.fluxData; % Cultivation data
% zeroFlux = data.zeroFlux; % List of exchange reactions that should not carry any flux, as these metabolites are widely assumed not to be excreted
% maxGrate = data.maxGrate; % Maximum growth rates

fluxData = loadFluxData(fullfile(basePath,'data','bayesianFluxData.tsv'));
fluxData.biomass = modelAdapter.params.bioRxn;
maxGrate = loadFluxData(fullfile(basePath,'data','bayesianMaxGrowth.tsv'));
maxGrate.biomass = modelAdapter.params.bioRxn;
zeroFlux = table2cell(readtable(fullfile(basePath,'data','bayesianZeroExch.tsv'), 'Delimiter', '\t', 'FileType','delimitedtext'));

% get carbonnum for each exchange rxn to further calculation of error
if ~isfield(ecModel,'excarbon')
    ecModel = addCarbonNum(ecModel);
    ecModel.excarbon(ecModel.excarbon == 0) = 1;
end

%these will be updated in the loop below
kcats = ecModel.ec.kcat;
D     = numel(kcats);

rmse = abc_max(ecModel,fluxData,maxGrate,zeroFlux);
fprintf('RMSE with prior kcats: %.2f.\n', rmse)

rmseTop   = rmse;
kcatTop   = kcats;
rmseTrace = rmse;
kcatTrace = kcats;
stdTrace  = kcatStd;

PB1 = ProgressBar2(maxGenerations, ['Run through ' num2str(maxGenerations) ' generations'], 'gui');

% Switch off default carbon source, will be set in each sample
tmpModel = setParam(ecModel,'lb',modelAdapter.params.c_source,0);

% Prepare for low-rank + residual proposal kernel
U_r = [];              % D×r PCA basis
sqrtLambda_r = [];     % r×r diagonal matrix with sqrt eigenvalues (inflated)
rEff = 0;              % effective rank
useLowRankKernel = true;

%% MAIN ABC-SMC LOOP
generation = 1;
while rmse > rmseThreshold
    if generation <= maxGenerations
        count(PB1)
        fprintf('Running iteration %d of %d. ', generation, maxGenerations)

        % Sampling
        if generation == 1
            % Define randomKcats via lognormal sampling around priors
            N = samples1;
            targetAccept = targetAcccept1;
            % randomKcats = arrayfun(@getrSample, kcats, kcatStd, repmat(N, length(kcats), 1), 'UniformOutput', false);
            % randomKcats = cell2mat(randomKcats);

            % Space‑filling first generation (better coverage than i.i.d. lognormal)
            % Replace purely i.i.d. lognormal draws with a Sobol (or LHS) design in log‑space, then map by exp.
            p = sobolset(D,'Skip',1e3,'Leap',1e2);
            U = net(p,N)';
            % Transform each dimension by the lognormal CDF inverse with (mu, sigma_log)
            mu_log    = log(max(kcats, eps));
            sigma_log = sqrt(log(1 + (kcatStd ./ max(kcats, eps)).^2));
            thetaProp = mu_log + sigma_log .* erfinv(2*U-1) * sqrt(2);
            randomKcats = exp(thetaProp);

        else
            if generation < 6
                N = samples2_5;
                targetAccept = targetAcccept2_5;
            else
                N = samples6_end;
                targetAccept = targetAcccept6_end;
            end

            % Define randomKcats by sampling around previous accepted
            % solutions using a full-covariance Guassian kernel in log
            % space, ABC-PMC
            % Randomly pick N columns with accepted kcat values
            parent_idx = randi(size(kcatTop,2), [1 N]);
            parents = log(kcatTop(:, parent_idx));

            if useLowRankKernel && rEff > 0
                % Low-rank kernel + residual proposal
                % Subspace noise (correlated along learned PCs)
                Zr = randn(rEff, N);                 % r×N
                % Residual isotropic noise to keep exploration outside the subspace
                E  = randn(D, N);                    % D×N

                % θ_new = log(θ_parent) + U_r * sqrtΛ_r * N(0, I_r) + sqrt(τ) * N(0, I_D)
                thetaProp = parents + U_r * (sqrtLambda_r * Zr) + sqrt(tauResidual) * E;

                % Map back to linear space
            else
                % Fallback: Compute Cholesky factor of the log-space
                % covariance SigmaLog, Stabilize with 1e-12*i
                L = chol(SigmaLog + 1e-12*eye(D), 'lower');
                % Draw normal noise for each proposal and correlate via L
                Z = randn(D, N);
                thetaProp = parents + L * Z;
            end

            % Map back to linear space
            randomKcats = exp(thetaProp);
        end

        if any(randomKcats <= 0, 'all')
            warning('randomKcats contains non-positive values after sampling; enforcing floor.')
            randomKcats = max(randomKcats, realmin);
        end

        %% Evaluate RMSE for each proposed sample
        newRmse  = zeros(N,1);
        PB2 = ProgressBar2(N, ['Simulate ' num2str(N) ' models with random kcats'], 'gui');

        parfor j = 1:N
            ecModelIter         = tmpModel;
            ecModelIter.ec.kcat = randomKcats(:,j);
            ecModelIter         = applyKcatConstraints(ecModelIter);
            newRmse(j)          = abc_max(ecModelIter,fluxData,maxGrate,zeroFlux);
            count(PB2)
        end

        % Leave out zero rmse results: model was unsolvable
        zeroIdx = (newRmse == 0);
        newRmse(zeroIdx) = [];
        randomKcats(:,zeroIdx) = [];

        % Combine with results from previous generation
        rmse = [newRmse; rmseTop];
        kcat = [randomKcats, kcatTop];

        % Accept samples based on targetAccept percentile of the RMSE
        % distribution (epsilon)
        epsilon = prctile(rmse, targetAccept);
        acc_idx = find(rmse <= epsilon);

        % Ensure a reasonable number of accepted samples
        minCount = max(1, floor(minKeep * numel(rmse)));
        maxCount = max(1, floor(maxKeep * numel(rmse)));

        if numel(acc_idx) < minCount
            % Relax epsilon slightly until min_keep is reached or capped attempts
            relaxFactor = 1.05; attempts = 0;
            while numel(acc_idx) < minCount && attempts < 20
                epsilon = epsilon * relaxFactor;
                acc_idx = find(rmse <= epsilon);
                attempts = attempts + 1;
            end
        end
        if numel(acc_idx) > maxCount
            [~,ord] = sort(rmse(acc_idx), 'ascend');
            acc_idx = acc_idx(ord(1:maxCount));
        end

        % Subset accepted
        rmseTop = rmse(acc_idx);
        kcatTop = kcat(:, acc_idx);

        %% Define means and standard deviations from accepted samples
        ss      = num2cell(kcatTop', 1);
        [a,b]   = arrayfun(@updateprior, ss);
        kcats   = transpose(a);
        kcatStd = transpose(b);

        %% Build new covariance matrix in log-space, to be used for next sampling
        thetaAcc = log(kcatTop);

        % Remove outliers, by filtering out samples whose z-scores had a
        % Median Absolute Deviation (MAD) of 6 or more
        z = abs(thetaAcc - median(thetaAcc,2)) ./ (mad(thetaAcc,1,2) + 1e-12);
        keepMask = median(z,1) < 6;
        % Fallback if everything gets filtered away
        if ~any(keepMask)
            warning('MAD filter removed all samples; disabling filtering this generation.');
            keepMask = true(1, size(thetaAcc,2));
        end
        thetaClean = thetaAcc(:, keepMask);

        % Determine empirical covariance of samples who were retained
        Cemp = cov(thetaClean');

        % Reduce noise in Cemp, through Ledoit-Wolf shrinkage towards a
        % diagonal covariance
        alphaLW = 0.1;
        SigmaLog = (1 - alphaLW) * Cemp + alphaLW * diag(diag(Cemp));

        if useLowRankKernel
            Kacc = size(thetaClean, 2);
            if Kacc >= 5   % need at least a handful of accepted samples
                % Center columns
                muLog = mean(thetaClean, 2);
                Xc = thetaClean - muLog;

                % Econ SVD gives principal directions of the sample covariance
                % cov = (Xc*Xc')/(Kacc-1) -> U * diag(sing) * U' where sing are eigenvalues
                [U, S, ~] = svd(Xc, 'econ');

                if ~isempty(S)
                    % Eigenvalues of covariance
                    sing = diag(S).^2 / max(1, (Kacc - 1));  % vector length = rank(Xc)

                    % Choose rank by variance fraction and rMax
                    cume = cumsum(sing) / max(eps, sum(sing));
                    rVar = find(cume >= varFrac, 1, 'first');
                    if isempty(rVar), rVar = length(sing); end
                    rEff = min([rVar, rMax, length(sing)]);

                    if rEff >= 1
                        U_r = U(:, 1:rEff);
                        % sqrt of eigenvalues for subspace sampling, with exploration inflation
                        sqrtLambda_r = diag( sqrt( cExpl * sing(1:rEff) ) );

                        % Optional: adapt residual variance to average discarded spectrum
                        if rEff < length(sing)
                            tauAdapt = mean(sing(rEff+1:end));
                        else
                            tauAdapt = 0;
                        end
                        % Keep at least the configured floor
                        tauResidual = max(tauResidual, 0.1 * tauAdapt);
                    else
                        % No informative subspace → disable low-rank this generation
                        U_r = []; sqrtLambda_r = []; rEff = 0;
                    end
                else
                    U_r = []; sqrtLambda_r = []; rEff = 0;
                end
            else
                % Too few accepted → fallback on LW+chol next generation
                U_r = []; sqrtLambda_r = []; rEff = 0;
            end
        end

        %% Track progress (use best, not first)
        [bestRMSE, bestIdx] = min(rmseTop);
        rmseTrace = [rmseTrace, bestRMSE];
        kcatTrace = [kcatTrace, kcats];
        stdTrace  = [stdTrace,  kcatStd];

        % Set a feasible/best point for next iteration's model baseline
        tmpModel.ec.kcat = kcatTop(:, bestIdx);
        tmpModel = applyKcatConstraints(tmpModel);

        fprintf('Accepted %d / %d, avg RMSE (accepted): %.2f, best: %.2f.\n', ...
            numel(rmseTop), numel(rmse), mean(rmseTop), bestRMSE)

        generation = generation + 1;
    else
        fprintf('Halted due to reaching maximum generation limit. Returning best posterior kcats.\n')
        break
    end
end

% Return best posterior kcats (best among last accepted)
[~, bestIdx] = min(rmseTop);
ecModel.ec.kcat = kcatTop(:, bestIdx);
ecModel = applyKcatConstraints(ecModel);
fprintf('Final RMSE: %.2f.\n', rmseTop(bestIdx))
end

function [mu,sigma] = updateprior(x,defaultCV)
% updateprior
%   Calculates a new distribution from the provided kcat values
%
% Input:
%   x       kcat values
%
% Output:
%   mu      mean
%   sigma   standard deviation

if nargin<2
    defaultCV = 0.25;
end

if iscell(x), x = x{:}; end

% Remove non-positive values—they cannot be logged
n_before = numel(x);
x = x(x > 0);
if isempty(x)
    error('x cannot be empty or contain only non-positive values.');
end
if numel(x) < n_before
    warning('Removed %d non-positive values before fitting.', n_before - numel(x));
end

if isscalar(x)
    mu      = x;
    sigma   = x * defaultCV;
else
    pd      = fitdist(log(x),'normal');
    mu    = exp(pd.mu + 0.5 * pd.sigma^2);
    sigma = sqrt( (exp(pd.sigma^2) - 1) * exp(2*pd.mu + pd.sigma^2) );
end
end
