function [ecModel, rmseTrace, kcatTrace, stdTrace] = bayesianSensitivityTuning(ecModel,kcatStd,modelAdapter)
% bayesianSensitivityTuning
%   Modifies kcats to better fit experimental data. Currently only works with
%   light models.
%
% Input:
%   ecModel         ecModel that was generated by makeEcModel, or loaded from
%                   an earlier run. Not compatible with ecModels generated by
%                   earlier GECKO versions (pre 3.0).
%   kcatStd         vector of same length as ecModel.ec.kcat, with the
%                   initial standard deviations (SD) for the kcat values.
%                   By default, kcatStd is set by multiplying kcat values
%                   with params.bayesian.initSDmultiplDef, or by source-
%                   specific multipliers specified in params.bayesian.
%                   kcatSources and params.bayesian.initSDmultipl. Instead,
%                   it is also possible to provide a custom kcatStd vector.
%   modelAdapter    a loaded model adapter (Optional, will otherwise use the
%                   default model adapter).
%
% Output:
%   model           ecModel with new kcats, not applied.
%
if nargin < 3 || isempty(modelAdapter)
    modelAdapter = ModelAdapterManager.getDefault();
    if isempty(modelAdapter)
        error('Either send in a modelAdapter or set the default ecModel adapter in the ModelAdapterManager.')
    end
end

%% Load hyperparameters
params = modelAdapter.params;
initSDmultiplDef    = params.bayesian.initSDmultiplDef;
kcatSources         = params.bayesian.kcatSources;
initSDmultipl       = params.bayesian.initSDmultipl;
scheduleGenerations = params.bayesian.scheduleGenerations;
scheduleSamples     = params.bayesian.scheduleSamples;
scheduleTarget      = params.bayesian.scheduleTarget;
minKeep             = params.bayesian.minKeep;
rMax                = params.bayesian.rMax;
cExpl               = params.bayesian.cExpl;
tauResidual         = params.bayesian.tauResidual;
rmseThreshold       = params.bayesian.rmseThreshold;
maxGenerations      = params.bayesian.maxGenerations;

%% Define initial kcat distributions
if nargin < 2 || isempty(kcatStd)
    kcatStd     = ecModel.ec.kcat .* initSDmultiplDef;
    for i = 1:numel(kcatSources)
        selKcats            = strcmpi(ecModel.ec.source,kcatSources{i});
        kcatStd(selKcats)   = ecModel.ec.kcat(selKcats) .* initSDmultipl(i);
    end
end

%% Load data
[fluxData, maxGrate, zeroFlux] = loadBayesianData(modelAdapter);

% get carbonnum for each exchange rxn to further calculation of error
if ~isfield(ecModel,'excarbon')
    ecModel = addCarbonNum(ecModel);
    ecModel.excarbon(ecModel.excarbon == 0) = 1;
end

%these will be updated in the loop below
kcats = ecModel.ec.kcat;
D     = numel(kcats);

rmse = abc_max(ecModel,fluxData,maxGrate,zeroFlux,modelAdapter);
fprintf('RMSE with prior kcats: %.2f.\n', rmse)

rmseTop   = rmse;
kcatTop   = kcats;
rmseTrace = rmse;
kcatTrace = kcats;
stdTrace  = kcatStd;

PB1 = ProgressBar2(maxGenerations, ['Run through ' num2str(maxGenerations) ' generations'], 'gui');

% Switch off default carbon source, will be set in each sample
tmpModel = setParam(ecModel,'lb',modelAdapter.params.c_source,0);

% Prepare for low-rank + residual proposal kernel
U_r = [];              % D×r PCA basis
sqrtLambda_r = [];     % r×r diagonal matrix with sqrt eigenvalues (inflated)
rEff = 0;              % effective rank
useLowRankKernel = true;

%% MAIN ABC-SMC LOOP
generation = 1;
while rmse > rmseThreshold
    if generation <= maxGenerations
        fprintf('Running iteration %d of %d. ', generation, maxGenerations)

        % Define N and targetFrac dependent on the generation
        schedulePos = find(generation >= scheduleGenerations, 1, 'last');
        N           = scheduleSamples(schedulePos);
        targetFrac  = scheduleTarget(schedulePos); % Acceptance fraction

        % Sampling
        if generation == 1
            % Define randomKcats via lognormal sampling around priors
            randomKcats = arrayfun(@getrSample, kcats, kcatStd, repmat(N, length(kcats), 1), 'UniformOutput', false);
            randomKcats = cell2mat(randomKcats);
        else
            % Define randomKcats by sampling around previous accepted
            % solutions using a full-covariance Guassian kernel in log
            % space, ABC-PMC
            % Randomly pick N columns with accepted kcat values
            parent_idx = randi(size(kcatTop,2), [1 N]);
            parents = log(kcatTop(:, parent_idx));

            if useLowRankKernel && rEff > 0
                % Low-rank kernel + residual proposal
                % Subspace noise (correlated along learned PCs)
                Zr = randn(rEff, N);                 % r×N
                % Residual isotropic noise to keep exploration outside the subspace
                E  = randn(D, N);                    % D×N

                % θ_new = log(θ_parent) + U_r * sqrtΛ_r * N(0, I_r) + sqrt(τ) * N(0, I_D)
                thetaProp = parents + U_r * (sqrtLambda_r * Zr) + sqrt(tauResidual) * E;

                % Map back to linear space
            else
                % Fallback: Compute Cholesky factor of the log-space
                % covariance SigmaLog, Stabilize with 1e-12*i
                L = chol(SigmaLog + 1e-12*eye(D), 'lower');
                % Draw normal noise for each proposal and correlate via L
                Z = randn(D, N);
                thetaProp = parents + L * Z;
            end

            % Map back to linear space
            randomKcats = exp(thetaProp);
        end

        if any(randomKcats <= 0, 'all')
            warning('randomKcats contains non-positive values after sampling; enforcing floor.')
            randomKcats = max(randomKcats, realmin);
        end

        %% Evaluate RMSE for each proposed sample
        newRmse  = zeros(N,1);
        PB2 = ProgressBar2(N, ['Simulate ' num2str(N) ' models with random kcats'], 'gui');

        parfor j = 1:N
            ecModelIter         = tmpModel;
            ecModelIter.ec.kcat = randomKcats(:,j);
            ecModelIter         = applyKcatConstraints(ecModelIter);
            newRmse(j)          = abc_max(ecModelIter,fluxData,maxGrate,zeroFlux,modelAdapter);
            count(PB2)
        end

        % Leave out zero rmse results: model was unsolvable
        zeroIdx = (newRmse == 0);
        newRmse(zeroIdx) = [];
        randomKcats(:,zeroIdx) = [];

        % Combine with results from previous generation
        rmse = [newRmse; rmseTop];
        kcat = [randomKcats, kcatTop];

        % Suggested number of accepted samples
        targetCount = max(1, round(targetFrac * numel(rmse)));

        % Sort RMSE ascending (best first)
        [~, ord] = sort(rmse, 'ascend');

        % Soft guard: check if RMSE curve is flat → soften selection
        if generation > 5
            lastWindow = rmseTrace(end-4:end); % Check last 5 RMSE
            if max(lastWindow) - min(lastWindow) < 1e-6
                % Plateau detected → relax selection slightly
                targetCount = round(targetCount * 1.3);
            end
        end

        % At least keep minKeep samples
        targetCount  = max(targetCount, minKeep);

        % Final accepted indices
        acc_idx = ord(1:targetCount);

        % Subset accepted samples
        rmseTop = rmse(acc_idx);
        kcatTop = kcat(:, acc_idx);

        %% Define means and standard deviations from accepted samples
        ss      = num2cell(kcatTop', 1);
        [a,b]   = arrayfun(@updateprior, ss);
        kcats   = transpose(a);
        kcatStd = transpose(b);

        %% Build new covariance matrix in log-space, to be used for next sampling
        thetaAcc = log(kcatTop);

        % Remove outliers, by filtering out samples whose z-scores had a
        % Median Absolute Deviation (MAD) of 6 or more
        z = abs(thetaAcc - median(thetaAcc,2)) ./ (mad(thetaAcc,1,2) + 1e-12);
        keepMask = median(z,1) < 6;
        % Fallback if everything gets filtered away
        if ~any(keepMask)
            warning('MAD filter removed all samples; disabling filtering this generation.');
            keepMask = true(1, size(thetaAcc,2));
        end
        thetaClean = thetaAcc(:, keepMask);

        % Determine empirical covariance of samples who were retained
        Cemp = cov(thetaClean');

        % Reduce noise in Cemp, through Ledoit-Wolf shrinkage towards a
        % diagonal covariance
        alphaLW = 0.1;
        SigmaLog = (1 - alphaLW) * Cemp + alphaLW * diag(diag(Cemp));

        if useLowRankKernel
            Kacc = size(thetaClean, 2);
            if Kacc >= 5   % need at least a handful of accepted samples
                % Center columns
                muLog = mean(thetaClean, 2);
                Xc = thetaClean - muLog;

                % Econ SVD gives principal directions of the sample covariance
                % cov = (Xc*Xc')/(Kacc-1) -> U * diag(sing) * U' where sing are eigenvalues
                [U, S, ~] = svd(Xc, 'econ');

                if ~isempty(S)
                    % Eigenvalues of covariance
                    sing = diag(S).^2 / max(1, (Kacc - 1));  % vector length = rank(Xc)

                    % Choose rank by variance fraction and rMax
                    cume = cumsum(sing) / max(eps, sum(sing));
                    rVar = find(cume >= varFrac, 1, 'first');
                    if isempty(rVar), rVar = length(sing); end
                    rEff = min([rVar, rMax, length(sing)]);

                    if rEff >= 1
                        U_r = U(:, 1:rEff);
                        % sqrt of eigenvalues for subspace sampling, with exploration inflation
                        sqrtLambda_r = diag( sqrt( cExpl * sing(1:rEff) ) );

                        % Optional: adapt residual variance to average discarded spectrum
                        if rEff < length(sing)
                            tauAdapt = mean(sing(rEff+1:end));
                        else
                            tauAdapt = 0;
                        end
                        % Keep at least the configured floor
                        tauResidual = max(tauResidual, 0.1 * tauAdapt);
                    else
                        % No informative subspace → disable low-rank this generation
                        U_r = []; sqrtLambda_r = []; rEff = 0;
                    end
                else
                    U_r = []; sqrtLambda_r = []; rEff = 0;
                end
            else
                % Too few accepted → fallback on LW+chol next generation
                U_r = []; sqrtLambda_r = []; rEff = 0;
            end
        end
        %% Track progress (use best, not first)
        [bestRMSE, bestIdx] = min(rmseTop);
        rmseTrace = [rmseTrace, bestRMSE];
        kcatTrace = [kcatTrace, kcats];
        stdTrace  = [stdTrace,  kcatStd];

        % Set a feasible/best point for next iteration's model baseline
        tmpModel.ec.kcat = kcatTop(:, bestIdx);
        tmpModel = applyKcatConstraints(tmpModel);

        fprintf('Accepted %d / %d, avg RMSE (accepted): %.2f, best: %.2f.\n', ...
            numel(rmseTop), numel(rmse), mean(rmseTop), bestRMSE)

        generation = generation + 1;
    else
        fprintf('Halted due to reaching maximum generation limit. Returning best posterior kcats.\n')
        break
    end
    count(PB1)
end

% Return best posterior kcats (best among last accepted)
[~, bestIdx] = min(rmseTop);
ecModel.ec.kcat = kcatTop(:, bestIdx);
ecModel = applyKcatConstraints(ecModel);
fprintf('Final RMSE: %.2f.\n', rmseTop(bestIdx))
end
