function [ecModel, rmseTrace, kcatTrace] = bayesianSensitivityTuning(ecModel,data,modelAdapter)
% bayesianSensitivityTuning
%   Modifies kcats to better fit experimental data. Currently only works with 
%   light models.
%
% Input:
%   ecModel         ecModel that was generated by makeEcModel, or loaded from
%                   an earlier run. Not compatible with ecModels generated by
%                   earlier GECKO versions (pre 3.0).
%   data
%   modelAdapter    a loaded model adapter (Optional, will otherwise use the
%                   default model adapter).
%   maxIterations   The maximum number of iterations to run (Optional, default 150)
%
% Output:
%   model           ecModel with new kcats, not applied.
%

if nargin < 3 || isempty(modelAdapter)
    modelAdapter = ModelAdapterManager.getDefault();
    if isempty(modelAdapter)
        error('Either send in a modelAdapter or set the default ecModel adapter in the ModelAdapterManager.')
    end
end

params = modelAdapter.params;
samplesPerGen       = params.bayesian.samplesPerGen; % Number of models in each generation
samplesFirstGen     = params.bayesian.samplesFirstGen; % Number of models in first generation
bestSamplesToKeep   = params.bayesian.bestSamplesToKeep; % Number of best-performing kcat samples to define posterior kcats
rmseThreshold       = params.bayesian.rmseThreshold; % RMSE threshold to halt and output best posterior kcats
maxGenerations      = params.bayesian.maxGenerations; % Maximum number of generations before returning best posterior kcats
basePath = params.path;

% fluxData = data.fluxData; % Cultivation data
% zeroFlux = data.zeroFlux; % List of exchange reactions that should not carry any flux, as these metabolites are widely assumed not to be excreted
% maxGrate = data.maxGrate; % Maximum growth rates

fluxData = table2cell(readtable(fullfile(basePath,'data','BayesianGrowthRatesOverFlow.csv')));
maxGrate = table2cell(readtable(fullfile(basePath,'data','BayesianMaxGrowth.csv')));
zeroFlux = table2cell(readtable(fullfile(basePath,'data','BayesianRxn2Block.csv'), 'Delimiter', ','));

% get carbonnum for each exchange rxn to further calculation of error
if ~isfield(ecModel,'excarbon')
    ecModel = addCarbonNum(ecModel);
end

% get carbonnum for each exchange rxn to further calculation of error
if ~isfield(ecModel,'excarbon')
    ecModel = addCarbonNum(ecModel);
end

%these will be updated in the loop below
kcats       = ecModel.ec.kcat;
kcatVar     = ones(length(ecModel.ec.kcat),1);

rmse        = abc_max(ecModel,fluxData,maxGrate,zeroFlux);
fprintf('RMSE with prior kcats: %.2f.\n',rmse)

rmseTop     = rmse;
kcatTop     = kcats;

rmseTrace   = rmse;
kcatTrace   = kcats;
varTrace    = kcatVar;

PB1 = ProgressBar2(maxGenerations,['Run through ' num2str(maxGenerations) ' generations'],'gui');

generation = 1;
while rmse > rmseThreshold

    if generation <= maxGenerations
        count(PB1)
        fprintf('Running iteration %d of %d. ', generation, maxGenerations)

        % First generation take more samples
        if generation == 1
            numberOfSamples = samplesFirstGen;
        else
            numberOfSamples = samplesPerGen;
        end

        prevRmse    = rmseTop;
        prevKcat    = kcatTop;
        newRmse     = zeros(numberOfSamples,1);

        % generate sample of kcats
        randomKcats = arrayfun(@getrSample,kcats,kcatVar,repmat(numberOfSamples,length(kcats),1),'UniformOutput',false);
        randomKcats = cell2mat(randomKcats);
        
        % simulate and measure RMSE
        PB2 = ProgressBar2(numberOfSamples,['Simulate ' num2str(numberOfSamples) ' models with random kcats'],'gui');
        parfor j = 1:numberOfSamples
            ecModelIter         = ecModel;
            ecModelIter.ec.kcat = randomKcats(:,j);
            ecModelIter         = applyKcatConstraints(ecModelIter);
            newRmse(j)          = abc_max(ecModelIter,fluxData,maxGrate,zeroFlux);
            count(PB2)
        end

        % Leave out zero rmse results: model was unsolvable
        zeroRmse                = newRmse == 0;
        newRmse(zeroRmse)       = [];
        randomKcats(:,zeroRmse) = [];

        % Combine with results from previous generation
        rmse = [newRmse,prevRmse];
        kcat = [randomKcats,prevKcat];

        % Select the kcat sets with lowest RMSE values
        [~,idx]     = sort(rmse,'ascend');
        rmseTop     = rmse(idx(1:bestSamplesToKeep));
        kcatTop     = kcat(:,idx(1:bestSamplesToKeep));

        % recalculate the mean and standard deviation
        ss          = num2cell(kcatTop',1);
        [a,b]       = arrayfun(@updateprior,ss);
        kcats       = a';
        kcatVar     = b';

        % Keep track of 
        rmseTrace   = [rmseTrace, rmseTop(1)];
        kcatTrace   = [kcatTrace, kcats];
        varTrace    = [varTrace, kcatVar];

        ecModel.ec.kcat = kcatTop(:,1);
        ecModel = applyKcatConstraints(ecModel);

        fprintf('Average RMSE of top 25 models: %.2f / RMSE of top model: %.2f.\n',mean(rmseTop), rmseTop(1))
        
        generation  = generation + 1;
    else
        fprintf('Halted due to reaching maximum generation limit. Returning best posterior kcats.\n')
        break
    end
end
ecModel.ec.kcat = kcatTop(:,1);
ecModel = applyKcatConstraints(ecModel);
fprintf('Final RMSE: %.2f.\n',rmseTop(1))
end
