function [ecModel, rmseTrace, kcatTrace, stdTrace] = bayesianSensitivityTuning(ecModel,kcatStd,modelAdapter)
% bayesianSensitivityTuning
%   Modifies kcats to better fit experimental data. Currently only works with 
%   light models.
%
% Input:
%   ecModel         ecModel that was generated by makeEcModel, or loaded from
%                   an earlier run. Not compatible with ecModels generated by
%                   earlier GECKO versions (pre 3.0).
%   kcatStd         vector of same length as ecModel.ec.kcat, with the
%                   initial standard deviations (SD) for the kcat values.
%                   By default, kcatStd is set at 10% of the kcat values 
%                   (as ecModel.ec.kcat./10). It might make sense to provide
%                   kcat-specific kcatStd, for instance based on the source
%                   of the kcat (if a source is more reliable, kcatStd
%                   should possibly be smaller).
%   modelAdapter    a loaded model adapter (Optional, will otherwise use the
%                   default model adapter).
%
% Output:
%   model           ecModel with new kcats, not applied.
%
if nargin < 3 || isempty(modelAdapter)
    modelAdapter = ModelAdapterManager.getDefault();
    if isempty(modelAdapter)
        error('Either send in a modelAdapter or set the default ecModel adapter in the ModelAdapterManager.')
    end
end

params = modelAdapter.params;
initSDmultiplDef    = params.bayesian.initSDmultiplDef;
kcatSources         = params.bayesian.kcatSources;
initSDmultipl       = params.bayesian.initSDmultipl;
scheduleGenerations = params.bayesian.scheduleGenerations;
scheduleSamples     = params.bayesian.scheduleSamples;
targetAccept        = params.bayesian.targetAccept; % RMSE percentile to accept in each iteration
minKeep             = params.bayesian.minKeep; % Minimum samples to keep
maxKeep             = params.bayesian.maxKeep; % Maximum samples to keep
alpha               = params.bayesian.alpha;             % exploit fraction
cExpl               = params.bayesian.cExpl;             % exploration inflation
freezeStage         = params.bayesian.freezeStage;       % freeze scale after this gen
sigmaFloorFrac      = params.bayesian.sigmaFloorFrac; % >=10% of initial
rMax                = params.bayesian.rMax;              % max PCA rank (field name fixed)
tauResidual         = params.bayesian.tauResidual;       % residual floor outside PCA subspace
rmseThreshold       = params.bayesian.rmseThreshold; % RMSE threshold to halt and output best posterior kcats
maxGenerations      = params.bayesian.maxGenerations; % Maximum number of generations before returning best posterior kcats

%% Define initial kcat distributions
if nargin < 2 || isempty(kcatStd)
    kcatStd     = ecModel.ec.kcat .* initSDmultiplDef;
    for i = 1:numel(kcatSources)
        selKcats            = strcmpi(ecModel.ec.source,kcatSources{i});
        kcatStd(selKcats)   = ecModel.ec.kcat(selKcats) .* initSDmultipl(i);
    end
end

%% Load data
[fluxData, maxGrate, zeroFlux] = loadBayesianData(modelAdapter);

% get carbonnum for each exchange rxn to further calculation of error
if ~isfield(ecModel,'excarbon')
    ecModel = addCarbonNum(ecModel);
    ecModel.excarbon(ecModel.excarbon == 0) = 1;
end

%% Prepare for ABC-SMC
%these will be updated in the loop below
kcats = ecModel.ec.kcat;

rmse = abc_max(ecModel,fluxData,maxGrate,zeroFlux,modelAdapter);
fprintf('RMSE with prior kcats: %.2f.\n', rmse)

rmseTop   = rmse;
kcatTop   = kcats;
rmseTrace = rmse;
kcatTrace = kcats;
stdTrace  = kcatStd;

PB1 = ProgressBar2(maxGenerations, ['Run through ' num2str(maxGenerations) ' generations'], 'gui');

% Switch off default carbon source, will be set in each sample
tmpModel = setParam(ecModel,'lb',modelAdapter.params.c_source,0);

% --- Proposal state (log-space) ---
D           = numel(kcats);
% initial log-space std from linear (mu,sigma) assuming lognormal
sigma0_log  = sqrt(log(1 + (kcatStd ./ max(kcats, eps)).^2));  % [D x 1]
U_r = []; Lambda = [];          % low-rank PCA basis for exploit kernel
U = [];
% sqrtLambda = []; rEff = 0; U = [];
sampleMethod = 'lowRankFunc'; %{'lowRankFunc','lowRankSnipp','cholsky'};
generation = 1;
while rmse > rmseThreshold
    if generation <= maxGenerations
        count(PB1)
        fprintf('Running iteration %d of %d. ', generation, maxGenerations)

        % Define N dependent on the generation
        schedulePos = find(generation >= scheduleGenerations, 1, 'last');
        N           = scheduleSamples(schedulePos);

        prevRmse = rmseTop;
        prevKcat = kcatTop;
        newRmse  = zeros(N,1);

        % Sampling
        if generation == 1
            % Per-parameter lognormal sampling around current mean
            randomKcats = arrayfun(@getrSample, kcats, kcatStd, repmat(N, length(kcats), 1), 'UniformOutput', false);
            randomKcats = cell2mat(randomKcats);
        else
            switch sampleMethod
                case 'lowRankFunc'

                    % Low-rank mixture proposal in log-space, centered on accepted parents
                    parent_idx = randi(size(kcatTop, 2), 1, N); % uniform resampling
                    parents    = kcatTop(:, parent_idx);         % [D x Nprop]

                    % Propose without forming full covariances:
                    randomKcats = proposeLowRankMixture(parents, U, Lambda, sigmaProp_log, sigma0_log, tauResidual, alpha, cExpl);

                case 'lowRankSnipp'

                    % Low-rank kernel + residual proposal
                    % Subspace noise (correlated along learned PCs)
                    Zr = randn(rEff, N);                 % r×N
                    % Residual isotropic noise to keep exploration outside the subspace
                    E  = randn(D, N);                    % D×N

                    % θ_new = log(θ_parent) + U_r * sqrtΛ_r * N(0, I_r) + sqrt(τ) * N(0, I_D)
                    thetaProp = parents + U_r * (sqrtLambda_r * Zr) + sqrt(tauResidual) * E;

                    % Map back to linear space
                    randomKcats = exp(thetaProp);
                case 'cholsky'

                    % Fallback: Compute Cholesky factor of the log-space
                    % covariance SigmaLog, Stabilize with 1e-12*i
                    L = chol(SigmaLog + 1e-12*eye(D), 'lower');
                    % Draw normal noise for each proposal and correlate via L
                    Z = randn(D, N);
                    thetaProp = parents + L * Z;
                    % Map back to linear space
                    randomKcats = exp(thetaProp);
            end
        end

        if any(randomKcats <= 0, 'all')
            warning('randomKcats contains non-positive values after sampling; enforcing floor.')
            randomKcats = max(randomKcats, realmin);
        end

        %% Evaluate RMSE for each proposed sample
        PB2 = ProgressBar2(N, ['Simulate ' num2str(N) ' models with random kcats'], 'gui');
        parfor j = 1:N
            ecModelIter         = tmpModel;
            ecModelIter.ec.kcat = randomKcats(:,j);
            ecModelIter         = applyKcatConstraints(ecModelIter);
            newRmse(j)          = abc_max(ecModelIter,fluxData,maxGrate,zeroFlux,modelAdapter);
            count(PB2)
        end

        % Leave out zero rmse results: model was unsolvable
        zeroRmse                = newRmse == 0;
        newRmse(zeroRmse)       = [];
        randomKcats(:,zeroRmse) = [];

        % Combine with results from previous generation
        rmse = [newRmse; prevRmse];
        kcat = [randomKcats, prevKcat];

        % Accept by epsilon (percentile)
        epsilon = prctile(rmse, targetAccept);
        acc_idx = find(rmse <= epsilon);

        % Ensure a reasonable number of accepted samples
        minCount = max(1, floor(minKeep * numel(rmse)));
        maxCount = max(1, floor(maxKeep * numel(rmse)));
        if numel(acc_idx) < minCount
            % Relax epsilon slightly until min_keep is reached or capped attempts
            relaxFactor = 1.05; attempts = 0; maxAttempts = 20;
            while numel(acc_idx) < minCount && attempts < maxAttempts
                epsilon = epsilon * relaxFactor;
                acc_idx = find(rmse <= epsilon);
                attempts = attempts + 1;
            end
        end
        if numel(acc_idx) > maxCount
            [~,ord] = sort(rmse(acc_idx), 'ascend');
            acc_idx = acc_idx(ord(1:maxCount));
        end

        % Subset accepted
        rmseTop = rmse(acc_idx);
        kcatTop = kcat(:, acc_idx);

        %% Define means and standard deviations from accepted samples
        ss      = num2cell(kcatTop', 1);
        [a,b]   = arrayfun(@updateprior, ss);
        kcats   = transpose(a);
        kcatStd = transpose(b);

        switch sampleMethod
            case 'lowRankFunc'

                % Build low-rank proposal (log-space) & freeze scale (sampling std)
                thetaAcc = log(kcatTop);                    % [D x Nacc]
                Xc       = thetaAcc - mean(thetaAcc,2);

                if size(Xc,2) >= 2
                    [Ufull, S, ~] = svd(Xc / sqrt(max(size(Xc,2)-1,1)), 'econ');
                    rAvail        = size(Ufull,2);
                    rUse          = min([rAvail, rMax, max(size(Xc,2)-1,1)]);
                    if rUse >= 1
                        U      = Ufull(:, 1:rUse);
                        Lambda = (diag(S(1:rUse,1:rUse))).^2;  % eigenvalues in log-space
                    else
                        U = zeros(D,0); Lambda = zeros(0,1);
                    end
                else
                    U = zeros(D,0); Lambda = zeros(0,1);
                end

                stds_obs = std(thetaAcc, 1, 2);            % [D x 1]
                if generation <= freezeStage
                    adaptFrac     = 0.5; % limited adaptation early
                    sigmaProp_log = max(adaptFrac*stds_obs + (1 - adaptFrac)*sigma0_log, ...
                        sigmaFloorFrac * sigma0_log);
                else
                    % Freeze: keep baseline multiplicative scale; learn only directions via U, Lambda
                    sigmaProp_log = max(sigma0_log, sigmaFloorFrac * sigma0_log);
                end
            case 'lowRankSnipp'
                thetaAcc = log(kcatTop);

                % Remove outliers, by filtering out samples whose z-scores had a
                % Median Absolute Deviation (MAD) of 6 or more
                z = abs(thetaAcc - median(thetaAcc,2)) ./ (mad(thetaAcc,1,2) + 1e-12);
                keepMask = median(z,1) < 6;
                % Fallback if everything gets filtered away
                if ~any(keepMask)
                    warning('MAD filter removed all samples; disabling filtering this generation.');
                    keepMask = true(1, size(thetaAcc,2));
                end
                thetaClean = thetaAcc(:, keepMask);
                Kacc = size(thetaClean, 2);
                if Kacc >= 5   % need at least a handful of accepted samples
                    % Center columns
                    muLog = mean(thetaClean, 2);
                    Xc = thetaClean - muLog;

                    % Econ SVD gives principal directions of the sample covariance
                    % cov = (Xc*Xc')/(Kacc-1) -> U * diag(sing) * U' where sing are eigenvalues
                    [U, S, ~] = svd(Xc, 'econ');

                    if ~isempty(S)
                        % Eigenvalues of covariance
                        sing = diag(S).^2 / max(1, (Kacc - 1));  % vector length = rank(Xc)

                        % Choose rank by variance fraction and rMax
                        cume = cumsum(sing) / max(eps, sum(sing));
                        rVar = find(cume >= varFrac, 1, 'first');
                        if isempty(rVar), rVar = length(sing); end
                        rEff = min([rVar, rMax, length(sing)]);

                        if rEff >= 1
                            U_r = U(:, 1:rEff);
                            % sqrt of eigenvalues for subspace sampling, with exploration inflation
                            sqrtLambda_r = diag( sqrt( cExpl * sing(1:rEff) ) );

                            % Optional: adapt residual variance to average discarded spectrum
                            if rEff < length(sing)
                                tauAdapt = mean(sing(rEff+1:end));
                            else
                                tauAdapt = 0;
                            end
                            % Keep at least the configured floor
                            tauResidual = max(tauResidual, 0.1 * tauAdapt);
                        else
                            % No informative subspace → disable low-rank this generation
                            U_r = []; sqrtLambda_r = []; rEff = 0;
                        end
                    else
                        U_r = []; sqrtLambda_r = []; rEff = 0;
                    end
                else
                    % Too few accepted → fallback on LW+chol next generation
                    U_r = []; sqrtLambda_r = []; rEff = 0;
                end
            case 'cholsky'
                thetaAcc = log(kcatTop);

                % Remove outliers, by filtering out samples whose z-scores had a
                % Median Absolute Deviation (MAD) of 6 or more
                z = abs(thetaAcc - median(thetaAcc,2)) ./ (mad(thetaAcc,1,2) + 1e-12);
                keepMask = median(z,1) < 6;
                % Fallback if everything gets filtered away
                if ~any(keepMask)
                    warning('MAD filter removed all samples; disabling filtering this generation.');
                    keepMask = true(1, size(thetaAcc,2));
                end
                thetaClean = thetaAcc(:, keepMask);

                % Determine empirical covariance of samples who were retained
                Cemp = cov(thetaClean');

                % Reduce noise in Cemp, through Ledoit-Wolf shrinkage towards a
                % diagonal covariance
                alphaLW = 0.1;
                SigmaLog = (1 - alphaLW) * Cemp + alphaLW * diag(diag(Cemp));
        end

        % Track progress (use best, not first)
        [bestRMSE, bestIdx] = min(rmseTop);
        rmseTrace = [rmseTrace, bestRMSE];
        kcatTrace = [kcatTrace, kcats];
        stdTrace  = [stdTrace,  kcatStd];

        % Set a feasible/best point for next iteration's model baseline
        tmpModel.ec.kcat = kcatTop(:, bestIdx);
        tmpModel = applyKcatConstraints(tmpModel);

        fprintf('Accepted %d / %d, avg RMSE (accepted): %.2f, best: %.2f.\n', ...
                numel(rmseTop), numel(rmse), mean(rmseTop), bestRMSE)

        generation = generation + 1;
    else
        fprintf('Halted due to reaching maximum generation limit. Returning best posterior kcats.\n')
        break
    end
end

% Return best posterior kcats (best among last accepted)
[~, bestIdx] = min(rmseTop);
ecModel.ec.kcat = kcatTop(:, bestIdx);
ecModel = applyKcatConstraints(ecModel);
fprintf('Final RMSE: %.2f.\n', rmseTop(bestIdx))
end

% ===================== Helper =====================

function proposals = proposeLowRankMixture(parents, U, Lambda, sigmaProp_log, sigma0_log, tau, alpha, cExpl)
% proposeLowRankMixture
%   Sample proposals in log-space using a mixture kernel:
%   Exploit: low-rank PCA shape + residual floor, with per-dim scale sigmaProp_log
%   Explore: inflated baseline diagonal (sigma0_log)
%   Both are centered on the parent in log-space.

[D, Nprop] = size(parents);
r = size(U, 2);

useExploit = rand(1, Nprop) < alpha;

% Exploit steps: (sqrt(tau)*E) + U*diag(sqrt(Lambda))*Z  then per-dim scale
nE = sum(useExploit);
if nE > 0
    Zr = randn(r, nE);
    Er = randn(D, nE);
    if r > 0
        y_exploit = bsxfun(@times, sqrt(tau), Er) + U * (bsxfun(@times, sqrt(Lambda), Zr));
    else
        y_exploit = bsxfun(@times, sqrt(tau), Er);
    end
    steps_exploit = bsxfun(@times, sigmaProp_log, y_exploit);
else
    steps_exploit = zeros(D,0);
end

% Explore steps: broad diagonal baseline
nX = sum(~useExploit);
if nX > 0
    Ee = randn(D, nX);
    steps_explore = bsxfun(@times, cExpl * sigma0_log, Ee);
else
    steps_explore = zeros(D,0);
end

% Assemble in original column order
steps = zeros(D, Nprop);
if nE > 0, steps(:,  useExploit) = steps_exploit; end
if nX > 0, steps(:, ~useExploit) = steps_explore; end

% Parent-centered in log-space, then back to linear space
proposals = exp(log(max(parents, realmin)) + steps);
proposals = max(proposals, realmin);
end
