function [ecModel, rmseTrace, kcatTrace, stdTrace] = bayesianSensitivityTuning(ecModel,kcatStd,modelAdapter)
% bayesianSensitivityTuning
%   Modifies kcats to better fit experimental data. Currently only works with
%   light models.
%
% Input:
%   ecModel         ecModel that was generated by makeEcModel, or loaded from
%                   an earlier run. Not compatible with ecModels generated by
%                   earlier GECKO versions (pre 3.0).
%   kcatStd         vector of same length as ecModel.ec.kcat, with the
%                   initial standard deviations (SD) for the kcat values.
%                   By default, kcatStd is set by multiplying kcat values
%                   with params.bayesian.initSDmultiplDef, or by source-
%                   specific multipliers specified in params.bayesian.
%                   kcatSources and params.bayesian.initSDmultipl. Instead,
%                   it is also possible to provide a custom kcatStd vector.
%   modelAdapter    a loaded model adapter (Optional, will otherwise use the
%                   default model adapter).
%
% Output:
%   model           ecModel with new kcats, not applied.
%
if nargin < 3 || isempty(modelAdapter)
    modelAdapter = ModelAdapterManager.getDefault();
    if isempty(modelAdapter)
        error('Either send in a modelAdapter or set the default ecModel adapter in the ModelAdapterManager.')
    end
end

%% Load hyperparameters
params = modelAdapter.params;
initSDmultiplDef    = params.bayesian.initSDmultiplDef;
kcatSources         = params.bayesian.kcatSources;
initSDmultipl       = params.bayesian.initSDmultipl;
scheduleGenerations = params.bayesian.scheduleGenerations;
scheduleSamples     = params.bayesian.scheduleSamples;
plateauWindow       = params.bayesian.plateauWindow;
plateauRelax        = params.bayesian.plateauRelax;
keepMinFrac         = params.bayesian.keepMinFrac;
keepMaxFrac         = params.bayesian.keepMaxFrac;
keepMinAbs          = params.bayesian.keepMinAbs;
rmseThreshold       = params.bayesian.rmseThreshold;
maxGenerations      = params.bayesian.maxGenerations;

%% Define initial kcat distributions
if nargin < 2 || isempty(kcatStd)
    kcatStd     = ecModel.ec.kcat .* initSDmultiplDef;
    for i = 1:numel(kcatSources)
        selKcats            = strcmpi(ecModel.ec.source,kcatSources{i});
        kcatStd(selKcats)   = ecModel.ec.kcat(selKcats) .* initSDmultipl(i);
    end
end

%% Load data
[fluxData, maxGrate, zeroFlux] = loadBayesianData(modelAdapter);

% get carbonnum for each exchange rxn to further calculation of error
if ~isfield(ecModel,'excarbon')
    ecModel = addCarbonNum(ecModel);
    ecModel.excarbon(ecModel.excarbon == 0) = 1;
end

%these will be updated in the loop below
kcats = ecModel.ec.kcat;
D     = numel(kcats);

rmse = abc_max(ecModel,fluxData,maxGrate,zeroFlux,modelAdapter);
fprintf('RMSE with prior kcats: %.2f.\n', rmse)

rmseTop   = rmse;
kcatTop   = kcats;
rmseTrace = rmse;
kcatTrace = kcats;
stdTrace  = kcatStd;

PB1 = ProgressBar2(maxGenerations, ['Run through ' num2str(maxGenerations) ' generations'], 'gui');

% Switch off default carbon source, will be set in each sample
tmpModel = setParam(ecModel,'lb',modelAdapter.params.c_source,0);

%% MAIN ABC-SMC LOOP
generation = 1;
while rmse > rmseThreshold
    if generation <= maxGenerations
        fprintf('Running iteration %d of %d. ', generation, maxGenerations)

        % Define N dependent on the generation
        schedulePos = find(generation >= scheduleGenerations, 1, 'last');
        N           = scheduleSamples(schedulePos);

        % Sampling
        if generation == 1
            % Define randomKcats via lognormal sampling around priors
            randomKcats = arrayfun(@getrSample, kcats, kcatStd, repmat(N, length(kcats), 1), 'UniformOutput', false);
            randomKcats = cell2mat(randomKcats);
            epsilon = inf;
        else
            % Define randomKcats by sampling around previous accepted
            % solutions using a full-covariance Guassian kernel in log
            % space, ABC-PMC
            % Randomly pick N columns with accepted kcat values
            parent_idx = randi(size(kcatTop,2), [1 N]);
            parents = log(kcatTop(:, parent_idx));

            % Compute Cholesky factor of the log-space covariance SigmaLog,
            % stabilize with 1e-12*i
            L = chol(SigmaLog + 1e-12*eye(D), 'lower');
            % Draw normal noise for each proposal and correlate via L
            Z = randn(D, N);
            thetaProp = parents + L * Z;

            % Map back to linear space
            randomKcats = exp(thetaProp);
        end

        if any(randomKcats <= 0, 'all')
            warning('randomKcats contains non-positive values after sampling; enforcing floor.')
            randomKcats = max(randomKcats, realmin);
        end

        %% Evaluate RMSE for each proposed sample
        newRmse  = zeros(N,1);
        PB2 = ProgressBar2(N, ['Simulate ' num2str(N) ' models with random kcats'], 'gui');

        parfor j = 1:N
            ecModelIter         = tmpModel;
            ecModelIter.ec.kcat = randomKcats(:,j);
            ecModelIter         = applyKcatConstraints(ecModelIter);
            newRmse(j)          = abc_max(ecModelIter,fluxData,maxGrate,zeroFlux,modelAdapter);
            count(PB2)
        end

        % Leave out zero rmse results: model was unsolvable
        zeroIdx = (newRmse == 0);
        newRmse(zeroIdx) = [];
        randomKcats(:,zeroIdx) = [];

        % Combine with results from previous generation
        rmse = [newRmse; rmseTop];
        kcat = [randomKcats, kcatTop];

        %% Adaptive percentile-based acceptance (auto-tunes epsilon)
        % Compute target accepted-count range relative to N, then clamp by absolute bounds
        targetMin = max(ceil(keepMinFrac * N), keepMinAbs);
        targetMax = ceil(keepMaxFrac * N);

        % Binary search over percentile to find an epsilon with accepted count in [targetMin, targetMax]
        low = 0; high = 100;
        epsilonCand = NaN;      % candidate epsilon
        for it = 1:12   % a few iterations suffice
            mid = (low + high) / 2;
            eps_mid = prctile(rmse, mid);
            k_mid   = sum(rmse <= eps_mid);
            if k_mid < targetMin
                low = mid;
            elseif k_mid > targetMax
                high = mid;
            else
                epsilonCand = eps_mid;
                break
            end
        end
        
        % Fallbacks if binary search did no hit the band
        if isnan(epsilonCand)
            % pick closer edge
            eps_low = prctile(rmse, low);
            k_low   = sum(rmse <= eps_low);
            eps_high = prctile(rmse, high);
            k_high   = sum(rmse <= eps_high);
        
            % choose the one closer to the band
            if abs(k_low - targetMin) <= abs(k_high - targetMax)
                epsilonCand = eps_low;
            else
                epsilonCand = eps_high;
            end
        end
        
        % Enforce monotone epsilon across generations (standard ABC–SMC)
        epsilon = min(epsilon, epsilonCand);
        
        % Plateau detection: if progress stalled, relax epsilon slightly (soft guard)
        if generation > plateauWindow
            lastWindow = rmseTrace(max(1, end - plateauWindow + 1) : end);
            if ~isempty(lastWindow) && (max(lastWindow) - min(lastWindow) < 1e-6)
                epsilon = epsilon * plateauRelax;
            end
        end
        
        % Accept all samples with RMSE <= epsilon (based on the same pool logic)
        acc_idx = find(rmse <= epsilon);
        
        % Ensure at least targetMin and not more than targetMax
        if numel(acc_idx) < targetMin
            [~, ord_all] = sort(rmse, 'ascend');
            acc_idx = ord_all(1:targetMin);
            epsilon = rmse(acc_idx(end)); % update epsilon with actual cutoff
        elseif numel(acc_idx) > targetMax
            [~, ord_acc] = sort(rmse(acc_idx), 'ascend');
            acc_idx = acc_idx(ord_acc(1:maxKeep));
            epsilon = rmse(acc_idx(end)); % update epsilon to the actual cutoff
        end

        % Subset accepted samples
        rmseTop = rmse(acc_idx);
        kcatTop = kcat(:, acc_idx);

        %% Define means and standard deviations from accepted samples
        ss      = num2cell(kcatTop', 1);
        [a,b]   = arrayfun(@updateprior, ss);
        kcats   = transpose(a);
        kcatStd = transpose(b);

        %% Build new covariance matrix in log-space, to be used for next sampling
        thetaAcc = log(kcatTop);

        % Remove outliers, by filtering out samples whose z-scores had a
        % Median Absolute Deviation (MAD) of 6 or more
        z = abs(thetaAcc - median(thetaAcc,2)) ./ (mad(thetaAcc,1,2) + 1e-12);
        keepMask = median(z,1) < 6;
        % Fallback if everything gets filtered away
        if ~any(keepMask)
            warning('MAD filter removed all samples; disabling filtering this generation.');
            keepMask = true(1, size(thetaAcc,2));
        end
        thetaClean = thetaAcc(:, keepMask);

        % Determine empirical covariance of samples who were retained
        Cemp = cov(thetaClean');

        % Reduce noise in Cemp, through Ledoit-Wolf shrinkage towards a
        % diagonal covariance
        alphaLW = 0.1;
        SigmaLog = (1 - alphaLW) * Cemp + alphaLW * diag(diag(Cemp));

        %% Track progress (use best, not first)
        [bestRMSE, bestIdx] = min(rmseTop);
        rmseTrace = [rmseTrace, bestRMSE];
        kcatTrace = [kcatTrace, kcats];
        stdTrace  = [stdTrace,  kcatStd];

        % Set a feasible/best point for next iteration's model baseline
        tmpModel.ec.kcat = kcatTop(:, bestIdx);
        tmpModel = applyKcatConstraints(tmpModel);

        fprintf('Accepted %d / %d, avg RMSE (accepted): %.2f, best: %.2f.\n', ...
            numel(rmseTop), numel(rmse), mean(rmseTop), bestRMSE)

        generation = generation + 1;
    else
        fprintf('Halted due to reaching maximum generation limit. Returning best posterior kcats.\n')
        break
    end
    count(PB1)
end

% Return best posterior kcats (best among last accepted)
[~, bestIdx] = min(rmseTop);
ecModel.ec.kcat = kcatTop(:, bestIdx);
ecModel = applyKcatConstraints(ecModel);
fprintf('Final RMSE: %.2f.\n', rmseTop(bestIdx))
end
