function [CarbonNum,EXfors,changedmets] = getcarbonnum(model,exrxn)
% getcarbonnum
%   Gets carbon numbers matching the model.
%
% Input:
%   model           ecModel that was generated by makeEcModel, or loaded from
%                   an earlier run. Not compatible with ecModels generated by
%                   earlier GECKO versions (pre 3.0).
%   exrxn           Exchange reaction to use for counting
% Output:
%   model           ecModel
%

% exrxn must be an exchange rxn and only contain one mets in the equation
[~,idx] = ismember(exrxn,model.rxns);
EXmets = model.S(:,idx);
% find all exchange mets
EXmetsIdx = zeros(length(exrxn),1);
for k = 1:length(EXmets(1,:))
    EXmetsIdx(k) = find(EXmets(:,k)); % 
end
EXfors = model.metFormulas(EXmetsIdx);
[Ematrix, elements] = getElementalComposition(EXfors,{'C'});
Ematrix = Ematrix(:,1);
changedmets = exrxn(isnan(Ematrix));
Ematrix(isnan(Ematrix)) = 1;
CarbonNum = Ematrix';
end