name: Tests

permissions:
      contents: write
      pull-requests: write
      repository-projects: write

on: [pull_request]

jobs:
  matlab-tests:
    runs-on: self-hosted

    steps:
      - name: Fetch GECKO
        uses: actions/checkout@v4

      - name: Fetch RAVEN
        uses: actions/checkout@v4
        with:
          repository: "SysBioChalmers/RAVEN"
          path: "RAVEN"

      - name: Run tests
        id: matlab-test
        run: |
          TEST_RESULTS=$(/usr/local/bin/matlab -nodisplay -nosplash -nodesktop -r "warning('off', 'MATLAB:rmpath:DirNotFound'); rmpath(genpath('/home/m/ecModels-dependencies/RAVEN')); rmpath(genpath('/home/m/actions-runner')); addpath(genpath('RAVEN')); GECKOInstaller.install; runtests('geckoCoreFunctionTests'); exit;" | awk 'NR>9 && !/^\.+/')
          PARSED_RESULTS="${TEST_RESULTS//'%'/'%25'}"
          PARSED_RESULTS="${PARSED_RESULTS//$'\n'/'<br>'}"
          PARSED_RESULTS="${PARSED_RESULTS//$'\r'/'<br>'}"
          echo "results=$PARSED_RESULTS" >> $GITHUB_OUTPUT

      - name: Post comment
        uses: NejcZdovc/comment-pr@v2
        with:
          file: "commentsFromTests.md"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          TEST_RESULTS: ${{steps.matlab-test.outputs.results}}
          GH_ACTION_RUN: ${{github.run_id}}
